### ISSUE TITLE
how to save“ icon.animate()” into *.gif ?  and Can you add Font data in Demo test?

### ISSUE THREAD

**Issue by Johnson-yue** [alexandre01/deepsvg#1]
Hi, thanks for your sharing, I am testing your repo

I want to know how to save result of `icon.animate()`  to *.gif ?

**Comment by alexandre01** [comment]
Hi! Thanks for your interest.

Just provide a value for the `file_path`argument. For example:
```python
icon.animate(file_path="animation.gif")
```

**Comment by Johnson-yue** [comment]
so quickly!!!, thank you 

And Would you add some more ipynb for Font-generation like 4.4 sections in paper?

**Comment by alexandre01** [comment]
haha 😉

Yes I'll add the pretrained model for font-generation very soon. However, we do not plan to release the font-dataset since it is very large and we do not own the rights on them. We recommend following the instructions below to download it by yourself:
https://github.com/magenta/magenta/tree/master/magenta/models/svg_vae

**Comment by Johnson-yue** [comment]
ok, I know , you can test by no rights fonts like, Source Han Sans font， or I can provide some other open-source Font file, if you want ？

**Comment by alexandre01** [comment]
Oh yes, sounds like a good solution to show some examples of interpolations between real glyphs in the notebook. Thanks for suggesting!

**Comment by Johnson-yue** [comment]
If you want to some font ，you can email to me。

when you add pretrained model for font-generation or same examples for font ， I will close this issue 。
have a nice day~

**Comment by alexandre01** [comment]
Added the pretrained models, mini dataset and a Jupyter notebook for font generation and interpolation 💪

https://github.com/alexandre01/deepsvg/blob/master/notebooks/fonts.ipynb

**Comment by alexandre01** [comment]
Added the pretrained models, mini dataset and a Jupyter notebook for font generation and interpolation 💪

https://github.com/alexandre01/deepsvg/blob/master/notebooks/fonts.ipynb

**Comment by Johnson-yue** [comment]
Thank you , I will try it soon
