### ISSUE TITLE
animation gif

### ISSUE THREAD

**Issue by UmarSpa** [alexandre01/deepsvg#2]
Amazing work. Can I ask you how did you make the gif animation in https://blog.alexandrecarlier.com/deepsvg/imgs/architecture.gif

what software did you use ?

**Comment by alexandre01** [comment]
Thank you very much!
I used Adobe AfterEffects which is considered to be the industry standard in 2D motion graphics. Needs a bit of practice, but once you know it, it's very flexible and powerful!
