### ISSUE TITLE
I can not open the pretrained model file

### ISSUE THREAD

**Issue by Johnson-yue** [alexandre01/deepsvg#4]
![Screenshot from 2020-07-27 11-00-15](https://user-images.githubusercontent.com/10268274/88499457-74677e00-cff8-11ea-82ab-e418278f7da2.png)

I think download is good，but I can not uncompressed this。

I try to some method but all failed， and I download twice the result is the same

How I fix it ？？

**Comment by alexandre01** [comment]
Hi @Johnson-yue,

The pretrained model file doesn't need to be uncompressed since it is directly done by PyTorch during the "load" method.

To see this, just type:

>>> torch.load("hierarchical_ordered_fonts.pth.tar")

What needs to be uncompressed though is the mini Fonts dataset (fonts_tensor.zip).

**Comment by Johnson-yue** [comment]
thanks， Sorry it is my fault
